#!/bin/sh
#
# Run a test that is supposed to fail.

# Places of executables
VERBOSE=0
USAGE="Usage: clonetest <testname>.t <new-testname>"
if [ $# != 2 ]; then
    echo "Exactly two parameters required"
    echo $USAGE
    exit 1
fi

FILE=$1
DEST=$2
BASENAME=`basename $FILE .t`
if [ $BASENAME = $FILE ]; then
    echo "The test to clone must be specified by its .t file"
    echo $USAGE
    exit 1
fi
EXISTS=0
FL=`echo $BASENAME.*`
for f in $FL; do
    DESTFILE=`echo $f | sed -e s/$BASENAME/$DEST/`
    if [ -e $DESTFILE ]; then
        echo "Destination file $DESTFILE already exists"
        EXISTS=1
    fi
done
if [ $EXISTS = 1 ]; then
    echo "I refuse to overwrite existing files. Goodbye."
    exit 1
fi
for f in $FL; do
    cp $f `echo $f | sed -e s/$BASENAME/$DEST/`
done
exit 0
