#!/bin/sh
# Run autoconf in all directories that have a configure.in file.
H=`pwd`
DIRS=`find $H -name configure.in -print | sed -e 's/configure.in//'`

for i in $DIRS; do cd $i; autoconf; echo -n .; done
echo
